const express=require("express")
const router= express.Router()
const taskController=require("../controllers/task")
const auth=require("../middlewares/auth")
router.get("/",auth.loggedMiddleware,taskController.fetchTasks)
router.get("/:id",auth.loggedMiddleware,taskController.getTaskById)
router.post("/",auth.loggedMiddleware, taskController.addTask)
router.patch("/:id",auth.loggedMiddleware,auth.isAdmin,taskController.updateTask)
router.delete("/:id",auth.loggedMiddleware,taskController.deleteTask)
module.exports=router